=== yonghong915/fib/codes/fib-boot/fib-framework/fib-gateway/src/main/resources/config/xsds/connector.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.fib.com/schema" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="connector">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="connection" minOccurs="0" maxOccurs="unbounded" xmlns="http://www.fib.com/schema" />
				<xs:element ref="reader" minOccurs="0" maxOccurs="unbounded" xmlns="http://www.fib.com/schema" />
				<xs:element ref="writer" minOccurs="0" maxOccurs="unbounded" xmlns="http://www.fib.com/schema" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="connection">
		<xs:complexType>
			<xs:attribute name="type" type="connectionType" use="required" xmlns="http://www.fib.com/schema" />
			<xs:attribute name="server-address" type="xs:string" />
			<xs:attribute name="port" type="xs:string" />
			<xs:attribute name="backlog" type="xs:int" />
			<xs:attribute name="comm-buffer-size" type="xs:int" />
		</xs:complexType>
	</xs:element>

	<xs:element name="reader">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" maxOccurs="unbounded" xmlns="http://www.fib.com/schema" />
				<xs:element ref="filter" maxOccurs="unbounded" xmlns="http://www.fib.com/schema" />
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="filter">
		<xs:complexType>
			<xs:attribute name="class" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="writer">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="filter" maxOccurs="unbounded" xmlns="http://www.fib.com/schema" />
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="parameter">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="connectionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SERVER" />
			<xs:enumeration value="CLIENT" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== yonghong915/fib/codes/fib-boot/fib-framework/fib-gateway/src/main/resources/config/upp/deploy/upp_cnaps2_recv/connector.xml
<?xml version="1.0" encoding="UTF-8"?>
<connector xmlns="http://www.fib.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.fib.com/schema 
	                    http://www.fib.com/schema/xsds/connector.xsd">

	<connection type="SERVER" port="1230" backlog="50" comm-buffer-size="8192" />

	<reader class="com.fib.gateway.channel.nio.reader.impl.LengthCheckNioReader">
		<parameter name="length-field-index">0</parameter>
		<parameter name="length-field-data-type">num</parameter>
		<parameter name="length-field-length">8</parameter>
		<parameter name="length-offset">-8</parameter>
		<filter class="com.fib.gateway.map.filter.LengthTrimFilter" />
	</reader>

	<writer class="com.fib.gateway.channel.nio.writer.impl.DefaultNioWriter">
		<filter class="com.fib.gateway.map.filter.LengthAppendFilter" />
	</writer>

</connector>
